routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ForumController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserControlController;


 Route::get('aktif-degil', function (){
     return view('front.offline');
 });
 Route::get('/clear', function() {
     Artisan::call('cache:clear');
     Artisan::call('config:cache');
     Artisan::call('view:clear');
     return "Cleared!";
 });

Route::any('/',[HomeController::class, 'index']);

Route::any('/home',[HomeController::class, 'index'])->name('home.page');

Route::post('login',[LoginController::class, 'customLogin'])->name('login.custom');

Route::post('sign-up',[LoginController::class, 'customRegister'])->name('signup.custom');

Route::get('logout',[LoginController::class, 'customLogout'])->name('logout');

Route::get('profile',[ProfileController::class, 'profile'])->name('profile');

Route::post('profile',[ProfileController::class,'update'])->name('update.profile');

Route::get('forum',[ForumController::class, 'index']);

 Route::post('forum',[ForumController::class, 'newDiscussing'])->name('create-discussing');

 Route::get('/iletisim', [\App\Http\Controllers\ContactController::class, 'contact'])->name('contact');

 Route::post('/iletisim', [\App\Http\Controllers\ContactController::class, 'contactpost'])->name('contact.post');

 Route::get('/blogs', [\App\Http\Controllers\BlogController::class, 'index'])->name('homepage');

 Route::get('/category/{category?}', [\App\Http\Controllers\BlogController::class, 'category'])->name('category');

 Route::post('/category/{category?}', [\App\Http\Controllers\BlogController::class, 'category'])->name('category');

 Route::get('/blog/{category}/{slug?}', [\App\Http\Controllers\BlogController::class, 'single'])->name('single');

 Route::post('/blog/{category}/{slug?}', [\App\Http\Controllers\BlogController::class, 'single'])->name('single');

 Route::get("forum/discussing={id?}",[ForumController::class,'getDiscussingDetail']);

 Route::post('forum/discussing={id}',[ForumController::class, 'newReply']);

 Route::post('forum/discussing/delete={reply_delete}', [ForumController::class,'deleteReply'])->name('delete.reply');

Route::post('forum/discussing/update={reply_update}', [ForumController::class,'updateReply'])->name('update.reply');

Route::post('forum/discussing/update-discussing={id}', [ForumController::class,'updateDiscussing'])->name('update.discussing');

Route::post('forum/discussing/fixed-discussing={fixed_id}', [ForumController::class,'fixDiscussing'])->name('fixed.discussing');

Route::post('forum/discussing/delete-discussing={delete_id}',[ForumController::class, 'deleteDiscussing'])->name('delete.discussing');

Route::get('forum/discussing={id}/liked/reply={reply_id}', [ForumController::class , 'likedReply']);

Route::get('forum', [ForumController::class,'index'])->name('filtre');

Route::resource('admin-users-control',UserControlController::class);

Route::post('admin-users-control',[UserControlController::class,'search'])->name('search.admin');

Route::resource('yazilarim', ArticleController::class);

Route::get('hakkimizda', function (){
    return view('hakkimizda');
});

Route::get('deneme', function (){
    return view('deneme');
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
class Article extends Model
{
    function getCategory(){
        return $this->hasOne('App\Models\BlogCategory','id','category_id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\BlogCategory;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Validator;
use Illuminate\Support\Facades\File;
use App\Models\Article;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (in_array(Auth::user()->user_type_id, [1, 3])) {
            $articles = Article::where('created_user_id', Auth::user()->id)->orderBy('created_at', 'ASC')->get();
            return view('articles.index', compact('articles'));
        }
        toastr()->error('Giriş izniniz bulunmamaktadır!');
        return redirect()->back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user_type_id = User::find(Auth::user()->id)->user_type_id;
        if (in_array($user_type_id, [1, 3])) {
            $categories = BlogCategory::all();
            return view('articles.create', compact('categories'));
        }
        toastr()->error('Giriş izniniz bulunmamaktadır!');
        return redirect()->back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), [
            'title' => 'min:3',
            'image' => 'required|image|mines:jpeg,png,jpg|max:2048',
            'content' => 'required',
        ]);
        if (in_array(Auth::user()->user_type_id, [1, 3])) {
            $article = new Article;
            $article->created_user_id = $request->created_user_id;
            $article->title = $request->title;
            $article->category_id = $request->category;
            $article->content = $request->article_content;
            $article->slug = Str::slug($request->title);

            if ($request->hasFile('image')) {
                $imageName = Str::slug($request->title) . '.' . $request->image->getClientOriginalExtension();
                $request->image->move(public_path('uploads'), $imageName);
                $article->image = '/uploads/' . $imageName;
            }
            $article->save();
            toastr()->success('Başarılı', 'Makale başarılı şekilde oluşturuldu.');
            return redirect()->route('yazilarim.index');
        }
        toastr()->error('Giriş izniniz bulunmamaktadır!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /** php artisan make:controller Back\ArticleController --resource
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (in_array(Auth::user()->user_type_id, [1, 3])) {
            $article = Article::findOrFail($id);
            $categories = BlogCategory::all();
            return view('articles.update', compact('categories', 'article'));
        }
        toastr()->error('Giriş izniniz bulunmamaktadır!');
        return redirect()->back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = Validator::make($request->all(), [
            'title' => 'min:3',
            'image' => 'image|mines:jpeg,png,jpg|max:2048',
        ]);
        if (in_array(Auth::user()->user_type_id, [1, 3])) {
            $article = Article::findOrFail($id);
            $article->created_user_id = $request->created_user_id;
            $article->title = $request->title;
            $article->category_id = $request->category;
            $article->content = $request->article_content;
            $article->slug = Str::slug($request->title);

            if ($request->hasFile('image')) {
                $imageName = Str::slug($request->title) . '.' . $request->image->getClientOriginalExtension();
                $request->image->move(public_path('uploads'), $imageName);
                $article->image = '/uploads/' . $imageName;
            }
            $article->save();
            toastr()->success('Başarılı', 'Makale başarılı şekilde güncellendi.');
            return redirect()->route('yazilarim.index');
        }
        toastr()->error('Giriş izniniz bulunmamaktadır!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {
        if (in_array(Auth::user()->user_type_id, [1, 3])) {
            $article = Article::findOrFail($id);
            if (File::exists($article->image)) {
                File::delete(public_path($article->image));
            }
            Article::find($id)->delete();
            toastr()->success('Makale, silinen makalelere taşındı.');
            return redirect()->route('yazilarim.index');
        }
        toastr()->error('Giriş izniniz bulunmamaktadır!');
        return redirect()->back();
    }

}

resources/views/articles/create.blade.php
@extends('Layouts.master')
@section('title', 'Makale Oluştur')
@section('content')
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">@yield('title')</h6>
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif
            <form method="post" action="{{ route('yazilarim.store') }}" enctype="multipart/form-data">
                @csrf
                <input type="hidden" name="created_user_id" value="{{ \Illuminate\Support\Facades\Auth::user()->id }}">
                <div class="form-group">
                    <label>Makale Başlığı</label>
                    <input type="text" name="title" class="form-control" required>
                </div>
                <div class="form-group">
                    <label>Makale Kategori</label>
                    <select class="form-control" name="category" required>
                        <option value="">Seçim Yapınız</option>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Makale Fotoğrafı</label>
                    <input type="file" name="image" class="form-control" required>
                </div>
                <div class="form-group">
                    <label>Makale İçeriği</label>
                    <textarea id="editor" name="article_content" class="form-control" rows="4"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Makaleyi Oluştur</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('css')
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection

@section('js')
    <!-- include summernote js -->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $('#editor').summernote({
            placeholder: 'Makelenizi Düzenleyiniz !!',
            tabsize: 2,
            height: 500
        });
    </script>
@endsection

resources/views/articles/index.blade.php
@extends('Layouts.master')
@section('title', 'Tüm Makaleler')
@section('content')
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">@yield('title')</h6>
            <h6 class="m-0 font-weight-bold float-right text-primary">
                <strong>{{ $articles->count() }} makale bulundu.</strong>
            </h6>
            <a href="{{ route('yazilarim.create') }}" title="Düzenle" class="btn btn-sm btn-primary">Yeni Yazı Ekle</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Fotoğraf</th>
                        <th>Makale Başlığı</th>
                        <th>Kategori</th>
                        <th>Hit</th>
                        <th>Oluşturulma Tarihi</th>
                        <th>İşlemler</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($articles as $article)
                        <tr>
                            <td>
                                <img src="{{ asset($article->image) }}" width="200">
                            </td>
                            <td>{{ $article->title }}</td>
                            <td>{{ $article->getCategory->name }}</td>
                            <td>{{ $article->hit }}</td>
                            <td>{{ $article->created_at->diffForHumans() }}</td>
                            <td>
                                <a href="{{ route('single', [$article->getCategory->slug,$article->slug]) }}" target="_blank" title="Görüntüle" class="btn btn-sm btn-success">Görüntüle</a>
                                <a href="{{ route('yazilarim.edit',$article->id) }}" title="Düzenle" class="btn btn-sm btn-primary">Düzenle</a>
{{--                                <a href="{{ route('yazilarim.destroy', $article->id) }}" title="Sil" class="btn btn-sm btn-danger">Sil</a>--}}
                                <form method="POST" action="{{ route('yazilarim.destroy', $article->id) }}">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}

                                    <div class="form-group">
                                        <input type="submit" class="btn btn-danger delete" value="Sil">
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script>
        $('.delete').click(function(e){
            e.preventDefault() // Don't post the form, unless confirmed
            if (confirm('Silmek için emin misiniz?')) {
                // Post the form
                $(e.target).closest('form').submit() // Post the surrounding form
            }
        });
    </script>
@endsection

resources/views/articles/update.blade.php
@extends('Layouts.master')
@section('title', $article->title.' makalesini güncelle')
@section('content')
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">@yield('title')</h6>
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif
            <form method="post" action="{{ route('yazilarim.update', $article->id) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <input type="hidden" name="created_user_id" value="{{ \Illuminate\Support\Facades\Auth::user()->id }}">
                <div class="form-group">
                    <label>Makale Başlığı</label>
                    <input type="text" name="title" class="form-control" value="{{ $article->title }}" required>
                </div>
                <div class="form-group">
                    <label>Makale Kategori</label>
                    <select class="form-control" name="category" required>
                        <option value="">Seçim Yapınız</option>
                        @foreach($categories as $category)
                            <option @if($article->category_id==$category->id) selected @endif value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Makale Fotoğrafı</label> <br>
                    <img src="{{ asset($article->image) }}" class="rounded img-thumbnail" width="300" alt="">
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="form-group">
                    <label>Makale İçeriği</label>
                    <textarea id="editor" name="article_content" class="form-control" rows="4">{!! $article->content !!}</textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Makaleyi Güncelle</button>
                </div>
            </form>
        </div>
    </div>
@endsection

{{--/*Sadece bu sayfada kullanılması gereken js ve css*/--}}
<!-- include summernote css/js -->
@section('css')
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection

@section('js')
    <!-- include summernote js -->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $('#editor').summernote({
            placeholder: 'Makelenizi Düzenleyiniz !!',
            tabsize: 2,
            height: 500
        });
    </script>
@endsection