routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\ForumController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserControlController;


 Route::get('aktif-degil', function (){
     return view('front.offline');
 });
 Route::get('/clear', function() {
     Artisan::call('cache:clear');
     Artisan::call('config:cache');
     Artisan::call('view:clear');
     return "Cleared!";
 });

Route::any('/',[HomeController::class, 'index']);

Route::any('/home',[HomeController::class, 'index'])->name('home.page');

Route::post('login',[LoginController::class, 'customLogin'])->name('login.custom');

Route::post('sign-up',[LoginController::class, 'customRegister'])->name('signup.custom');

Route::get('logout',[LoginController::class, 'customLogout'])->name('logout');

Route::get('profile',[ProfileController::class, 'profile'])->name('profile');

Route::post('profile',[ProfileController::class,'update'])->name('update.profile');

Route::get('forum',[ForumController::class, 'index']);

 Route::post('forum',[ForumController::class, 'newDiscussing'])->name('create-discussing');

 Route::get('/iletisim', [\App\Http\Controllers\ContactController::class, 'contact'])->name('contact');

 Route::post('/iletisim', [\App\Http\Controllers\ContactController::class, 'contactpost'])->name('contact.post');

 Route::get('/blogs', [\App\Http\Controllers\BlogController::class, 'index'])->name('homepage');

 Route::get('/category/{category?}', [\App\Http\Controllers\BlogController::class, 'category'])->name('category');

 Route::post('/category/{category?}', [\App\Http\Controllers\BlogController::class, 'category'])->name('category');

 Route::get('/blog/{category}/{slug?}', [\App\Http\Controllers\BlogController::class, 'single'])->name('single');

 Route::post('/blog/{category}/{slug?}', [\App\Http\Controllers\BlogController::class, 'single'])->name('single');

 Route::get("forum/discussing={id?}",[ForumController::class,'getDiscussingDetail']);

 Route::post('forum/discussing={id}',[ForumController::class, 'newReply']);

 Route::post('forum/discussing/delete={reply_delete}', [ForumController::class,'deleteReply'])->name('delete.reply');

Route::post('forum/discussing/update={reply_update}', [ForumController::class,'updateReply'])->name('update.reply');

Route::post('forum/discussing/update-discussing={id}', [ForumController::class,'updateDiscussing'])->name('update.discussing');

Route::post('forum/discussing/fixed-discussing={fixed_id}', [ForumController::class,'fixDiscussing'])->name('fixed.discussing');

Route::post('forum/discussing/delete-discussing={delete_id}',[ForumController::class, 'deleteDiscussing'])->name('delete.discussing');

Route::get('forum/discussing={id}/liked/reply={reply_id}', [ForumController::class , 'likedReply']);

Route::get('forum', [ForumController::class,'index'])->name('filtre');

Route::resource('admin-users-control',UserControlController::class);

Route::post('admin-users-control',[UserControlController::class,'search'])->name('search.admin');

Route::resource('yazilarim', ArticleController::class);

Route::get('hakkimizda', function (){
    return view('hakkimizda');
});

Route::get('deneme', function (){
    return view('deneme');
});

app/Http/Controllers/UserControlController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Discussing;
use App\Models\Reply;
use App\Models\User;
use App\Models\UserType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UserControlController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->user_type_id != 1){
            header('HTTP/1.1 404 Not Found');
            abort(404);
        }

        $userList= DB::table('users')->leftJoin('users_type', 'users.user_type_id', '=', 'users_type.user_type_id')->paginate(20);

        return view('UserControl/userList')->with(['list' => $userList]);


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $user_info = User::join('users_type', 'users_type.user_type_id', '=', 'users.user_type_id')->
        where('users.id', $id)->get();

        $tab = Discussing::join('users', 'created_user_id', '=', 'users.id')->
        where('users.id', $id)->get();

        $tab2 = Reply::join('users', 'user_id', '=', 'users.id')->
        where('users.id', $id)->get();

        $tab3 = Article::join('users', 'created_user_id', '=', 'users.id')->
        where('users.id', $id)->get();

        $userTypes = UserType::all();

        return view('UserControl/userDetail')->with(['profile',
            'user_info' => $user_info, 'tab' => $tab, 'tab2' => $tab2, 'tab3' => $tab3,'usersType' => $userTypes]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateUserType = User::find($request['userId'])->update(['user_tpye_id'=>$id]);
         if ($updateUserType == true){
             toastr()->success('Kullanıcı Tipi Güncellenmiştir', 'Kullanıcı Tipi');
             return redirect()->route('admin-users-control.show',$request['userId']);
         }
        toastr()->error('Güncellenemedi.');
        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Reply::where('user_id',$id)->delete();

        Discussing::where('created_user_id',$id)->delete();

        $deleteUserType = User::findOrFail($id)->delete();

        if ($deleteUserType == true){
               toastr()->success('Kullanıcı Güncelleme, Başarıyla Güncellenmiştir');
            return redirect()->route('admin-users-control.index');
        }
        toastr()->error('Silinemedi.');
        return redirect()->back();
    }

    public function search(Request $request)
    {
       $users = User::where('name','like',$request['search'])->get();

        return view('UserControl/userList')->with(['list' => $users]);
    }
}

resources/views/UserControl/master_user.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <title>
        SorunBM
    </title>
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    @yield('css')
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <link href="/css/nucleo-icons.css" rel="stylesheet" />
    <link href="/css/nucleo-svg.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <link id="pagestyle" href="/css/material-dashboard.css?v=3.0.4" rel="stylesheet" />
</head>

<body class="g-sidenav-show  bg-gray-200">
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="/admin-users-control">
            <img src="/images/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-white">SorunBM</span>
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white active bg-gradient-primary" href="/admin-users-control">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">table_view</i>
                    </div>
                    <span class="nav-link-text ms-1">Users</span>
                </a>
            </li>
        </ul>
    </div>
</aside>
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
        <div class="container-fluid py-1 px-3">
            <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                    <div class="input-group input-group-outline">
                        <input type="text" id="searchUser" name="search" class="form-control" placeholder="Kullanıcı adı giriniz">
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div>
        @yield('userList')
        @yield('userDetail')
    </div>
</main>
@yield('js')
<!--   Core JS Files   -->
<script src="/js/core/popper.min.js"></script>
<script src="/js/jquery-3.3.1.min.js"></script>
<script src="/js/core/bootstrap.min.js"></script>
<script src="/js/plugins/perfect-scrollbar.min.js"></script>
<script src="/js/plugins/smooth-scrollbar.min.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }


    $('#searchUser').keypress(function(event){
        let search = $('input[name=search]').attr('value');
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if(keycode == '13'){
            let _token = $('meta[name=csrf-token]').attr('content');
            $.ajax({
                url: "{{ route('search.admin') }}",
                type: 'post',
                data:{
                    _token:_token,
                    search:search
                },
                success: function(response) {
                    alert(search);
                }
            });
        }
    });

</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="/js/material-dashboard.min.js?v=3.0.4"></script>
</body>

</html>

resources/views/UserControl/userDetail.blade.php
@extends('UserControl/master_user')
@section('userDetail')
    @if($errors->any())
        <div class="alert alert-danger">
            @foreach($errors as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif
    <div class="container">
        <div class="float-right">
            <form method="POST" action="{{ route('admin-users-control.destroy', $user_info[0]->id) }}">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}

                <div class="form-group">
                    <input type="submit" class="btn btn-danger delete" value="Sil">
                </div>
            </form>
        </div>
        <div class="main-body">
            <div class="col-md-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="d-flex align-items-end text-center" style="float: right">
                            <img src="{{ URL::asset('images/icons8-user-50.png') }}" alt="Admin"
                                 class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>{{ $user_info[0]->nickname }}</h4>
                                <small>Üye Olduğu Tarih</small>
                                <h4>{{ $user_info[0]->created_at }}</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">İsim Soyisim</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{$user_info[0]->name}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{$user_info[0]->email}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Telefon</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{$user_info[0]->telephone}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-2">
                                <h6 class="mb-0">Kullanıcı Rolü</h6>
                            </div>
                            <div class="col-sm-3 text-secondary">
                                <form method="post" action="{{ route('admin-users-control.update',$user_info[0]->user_type_id) }}">
                                    @method('PUT')
                                    @csrf
                                    <input type="hidden" name="userId" id="userId" value="{{$user_info[0]->id}}">
                                    <select name="userType" id="userType">
                                        @foreach($usersType as $types)
                                            <option @if($types->user_type_id == $user_info[0]->user_type_id) selected @endif value="{{ $types->user_type_id }}">{{$types->user_type}}</option>
                                        @endforeach
                                    </select>
                                    <button class="btn" type="submit">güncelle</button>
                                </form>
                            </div>
                        </div>
                        <hr>
                    </div>
                </div>
            </div>
            <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                    <div class="card h-100">
                        <div class="card-body">
                            <h6 class="d-flex align-items-center mb-3"><i
                                    class="material-icons text-info mr-2"></i>Açtığı Konular</h6>
                            @if( count($tab) > 0)
                                @foreach($tab as $discussing)
                                    <small><a
                                            href="/forum/discussing={{ $discussing->discussing_id }}">{{ $discussing->discussing_title }}</a></small>
                                    <hr>
                                @endforeach
                        </div>
                        @else
                            <span class="mb-3 text-info"><a href="/forum"> Herhangi bir konunuz bulunmamaktadır!! konu oluşturmak Forum sayfamızı ziyaret edebilrisiniz..</a></span>
                        @endif
                    </div>
                </div>
                <div class="col-sm-6 mb-3">
                    <div class="card h-100">
                        <div class="card-body">
                            <h6 class="d-flex align-items-center mb-3"><i
                                    class="material-icons text-info mr-2"></i>Verdiği Yanıtlar</h6>
                            @if( count($tab2) > 0)
                                @foreach($tab2 as $replys)
                                    <small><a
                                            href="/forum/discussing={{ $replys['discussing_id'] }}">{{$replys->reply_text}}</a></small>
                                    <hr>
                                @endforeach
                        </div>
                        @else
                            <span class="mb-3 text-info"><a href="/forum"> Herhangi bir Yanıtınız bulunmamaktadır!! Yorum yapmak için tıklayınız.</a></span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script>
        $('.delete').click(function(e){
            e.preventDefault() // Don't post the form, unless confirmed
            if (confirm('Silmek için emin misiniz?')) {
                // Post the form
                $(e.target).closest('form').submit() // Post the surrounding form
            }
        });
    </script>
@endsection

resources/views/UserControl/userList.blade.php
@extends('UserControl/master_user')
@section('userList')
<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                        <h6 class="text-white text-capitalize ps-3">Kullanıcı listesi</h6>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Kullanıcı Adı</th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Kullanıcı Tipi</th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Üyelik Tarihi</th>
                                <th class="text-secondary opacity-7"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($list as $items)
                            <tr>
                                <td>
                                    <div class="d-flex px-2 py-1">
                                        <div class="d-flex flex-column justify-content-center">
                                            <h6 class="mb-0 text-sm">{{$items->name}}</h6>
                                            <p class="text-xs text-secondary mb-0">{{$items->email}}</p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <p class="text-xs font-weight-bold mb-0">{{$items->user_type}}</p>
                                </td>
                                <td class="align-middle text-center">
                                    <span class="text-secondary text-xs font-weight-bold">{{$items->created_at}}</span>
                                </td>
                                <td class="align-middle">
                                    <a href="{{ route('admin-users-control.show',$items->id) }}" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                        Detay
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <hr>
                        <div class="mt-1 d-flex align-items-center">
                            {{ $list->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection